<?php

namespace AppBundle\Repository;

/**
 * InscractiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscractiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
